### ISSUE TITLE
MemoryError: In RendererAgg: Out of memory

### ISSUE THREAD

**Issue by YingYa** [getzlab/SignatureAnalyzer#40]
The plot_mutational_signatures function takes up-to 600G memory to generate signature_contributions.pdf for pcawg_COMPOSITE.

**Comment by yoakiyama** [comment]
That's odd. I will take a look at the code and see where it is going wrong. Sorry for the trouble!

**Comment by yoakiyama** [comment]
The issue seemed to be coming from the rasterization, which can take lots of memory when the plot is large, which is often the case when using the composite spectra. We can go ahead and not rasterize to use less memory and allow the user to recreate the figure and rasterize as needed. Thanks for raising this point
