### ISSUE TITLE
How to applied two-step signature extraction strategy with SignatureAnalyzer for hyper-mutated samples

### ISSUE THREAD

**Issue by YingYa** [getzlab/SignatureAnalyzer#41]
Hi,

How to applied two-step signature extraction strategy with SignatureAnalyzer for hyper-mutated samples? Two-step signature extraction strategy was applied to PCAWG study in R scripts. 

How to make fake samples form the result generated by the SignatureAnalyzer (latest python version)?

Regards

**Comment by yoakiyama** [comment]
Hi @YingYa sorry I missed this post. If you would like to run a two-step signature extraction strategy consistent with the one used in the PCAWG study, you would first run SignatureAnalyzer on the non-hypermutants, then run a semi-supervised approach by adding "fake" samples to the mutational spectra for the hypermutant analysis. You can do this by simply adding N number of columns to your input spectra to force these signatures in the W matrix of the hypermutant run, then run SignatureAnalyzer in "spectra" mode using the flag `-t spectra`. Please let us know if you have any additional questions. Thank you

Best regards,
Yo Akiyama
