### ISSUE TITLE
Missing plot_results argument in CLI

### ISSUE THREAD

**Issue by madisonjordan** [getzlab/SignatureAnalyzer#46]
I have been running Signature Analyzer as part of a workflow and the process fails (value error: zero-size array ...) in the plotting section despite ARD completing successfully for certain datasets, which I'd still like to continue to process. The failure of this output causes the workflow to stop. 

I saw that there is the logic for plotting if the `plot_results` arg is set to true in `signatureanalyzer.py`. Would it be possible to have an argument for enabling/disabling the plotting function added in argparse for the CLI? 

Thank you for all your work so far. It's been running great on data I've tested otherwise.

**Comment by yoakiyama** [comment]
Hi Madison,

That's a good point -- I should definitely add this. As for the error itself, we've seen that come up when NMF only pulls 1 signature for all samples. Is this the case for you?

**Comment by madisonjordan** [comment]
Thanks for the response, Yo.

It seems like there are 3 signatures in the file generated, but two of them are very rare and would only be the most probable signature in only a small number of cases. It is mostly just the one signature. 
If it makes a difference, I have been running the 0.0.7 version installed from pip in a docker container. I noticed that the `_muts.py` and `__init__.py` have changed since the release of 0.0.7 on Mar 2, 2020. I need to talk to my supervisor about whether we should consider building from the latest changes in this GitHub repo.
