### ISSUE TITLE
A SignatureAnalyzer gpu docker image available?

### ISSUE THREAD

**Issue by ryao-mdanderson** [getzlab/SignatureAnalyzer#48]
Dear SignatureAnalyzer  team,

 I wonder if I can have a gpu version of the docker image to download? This will be helpful.

Thank you!

**Comment by ryao-mdanderson** [comment]
Greetings SignatureAnalyzer team,
@julianhess @francois-a @shankara-a @njharlen 
Please kindly let me know if there is a prebuild SignatureAnalyzer **gpu** docker image for download?

Thank you for your help.
Rong Yao

**Comment by ryao-mdanderson** [comment]
Greetings SignatureAnalyzer team, @julianhess @francois-a @shankara-a @njharlen 

Please advise if there is a prebuild SignatureAnalyzer gpu docker image for download?
This will be helpful.

Thank you,
Rong Yao

**Comment by yoakiyama** [comment]
Hi @ryao-mdanderson sorry for the incredibly slow response. We currently do not have a docker image for SignatureAnalyzer and do not have plans to provide one. However, you should be able to clone the repo in the Dockerfile and go from there
