### ISSUE TITLE
support other genomes like plant?

### ISSUE THREAD

**Issue by yjiang296** [getzlab/SignatureAnalyzer#54]
Hello developers, I was wondering whether this tool can support other genomes like rice genome? Thanks in advance.

**Comment by gpmoorhead1** [comment]
Hi, we currently only support human genome builds.

**Comment by gpmoorhead1** [comment]
Hi,
You can use other genomes by importing a 2bit genome build and assigning the "hg_build" to said import. It's also important to note that the reference signatures that the tool will compute similarity too might not be as meaningful, as those were discovered from the human genome.
